# Site settings
# in the templates available like {{ site.myvariable }}.
title: Welcome to Fitness Tree.
email: fitnesstreeindia@gmail.com
brand: Fitness Tree
headline: A holistic fitness studio that helps individuals attain the greatest gift of all -- that of good health.
description: > # this means to ignore newlines until "baseurl:"
  Official Site
baseurl: "www.fitnesstree.in" # the subpath of your site, e.g. /blog
url: "http://fitnesstree.in" # the base hostname & protocol for your site
copyright: 2017 Fitness Tree. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: fitnesstreeindia@gmail.com
phone: +91-9871366691

# Tracking
googleAnalitycsID: 

